name: "Build package"
description: "Build testplan package"
inputs:
  is_dev_build:
    description: "If true generate dev buildnumber"
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
    - uses: pnpm/action-setup@v3
      with:
        version: 8.10.4
    - run: |
        sudo apt install libkrb5-dev -y
        pip install --upgrade pip
        pip install --upgrade -r requirements-build.txt        
      shell: bash
    - run: CI=false doit -v2 build${{ (inputs.is_dev_build == 'true' && '_dev') || '' }}
      shell: bash
