# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
    - libkrb5-dev
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/en/conf.py


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements-rtd.txt
