#!/usr/bin/env python
"""Demonsrates attaching files to the Testplan report."""
import tempfile
import os
import sys

import testplan
from testplan.testing import multitest


@multitest.testsuite
class TestSuite(object):
    """Example test suite."""

    def __init__(self):
        """
        For example purposes, write out a temporary file to attach to the
        report. Realistically you would likely want to attach a file
        generated by the application you are testing.
        """
        with tempfile.NamedTemporaryFile(
                mode="w", suffix=".txt", delete=False) as tmpfile:
            tmpfile.write("testplan\n" * 100)
        self.tmpfile = tmpfile.name

    @multitest.testcase
    def test_attach(self, env, result):
        """Attaches a file to the report."""
        result.attach(self.tmpfile, description="Attaching a text file")

    @multitest.testcase
    def test_attach_again(self, env, result):
        """
        Attach the same file to the report again. This is allowed, only
        one copy of the file will be made under the attachments dir.
        """
        result.attach(self.tmpfile,
                      description="Attaching the same text file again")


@testplan.test_plan(name="AttachmentPlan")
def main(plan):
    """Define a Testplan with a single MultiTest."""
    plan.add(multitest.MultiTest(
        name="TestAttachments",
        suites=[TestSuite()]))


if __name__ == "__main__":
    res = main()
    sys.exit(res.exit_code)

