from collections import Counter

REPORT = {
    "status_reason": None,
    "counter": Counter({"total": 5, "unknown": 4, "passed": 1, "failed": 0}),
    "runtime_status": "ready",
    "tags": {},
    "timer": {},
    "category": "multitest",
    "status_override": None,
    "logs": [],
    "part": None,
    "status": "unknown",
    "entries": [
        {
            "status_reason": None,
            "counter": Counter(
                {"total": 3, "unknown": 2, "passed": 1, "failed": 0}
            ),
            "runtime_status": "ready",
            "tags": {},
            "timer": {},
            "category": "testsuite",
            "status_override": None,
            "logs": [],
            "part": None,
            "status": "unknown",
            "entries": [
                {
                    "status_reason": None,
                    "counter": Counter(
                        {"total": 3, "unknown": 2, "passed": 1, "failed": 0}
                    ),
                    "runtime_status": "ready",
                    "tags": {},
                    "timer": {},
                    "category": "parametrization",
                    "status_override": None,
                    "logs": [],
                    "part": None,
                    "status": "unknown",
                    "entries": [
                        {
                            "status_reason": None,
                            "suite_related": False,
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "description": None,
                            "runtime_status": "ready",
                            "tags": {},
                            "timer": {},
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "category": "testcase",
                            "status_override": None,
                            "logs": [],
                            "uid": "basic_case__arg_0",
                            "name": "basic_case <arg=0>",
                            "status": "unknown",
                            "type": "TestCaseReport",
                            "hash": 0,
                            "entries": [],
                        },
                        {
                            "status_reason": None,
                            "suite_related": False,
                            "counter": Counter(
                                {"passed": 1, "total": 1, "failed": 0}
                            ),
                            "description": None,
                            "runtime_status": "finished",
                            "tags": {},
                            "timer": {
                                "run": {
                                    "end": "2021-07-27T06:49:52.078141+00:00",
                                    "start": "2021-07-27T06:49:52.069275+00:00",
                                }
                            },
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "category": "testcase",
                            "status_override": None,
                            "logs": [],
                            "uid": "basic_case__arg_1",
                            "name": "basic_case <arg=1>",
                            "status": "passed",
                            "type": "TestCaseReport",
                            "hash": 0,
                            "entries": [
                                {
                                    "flag": "DEFAULT",
                                    "machine_time": "",
                                    "meta_type": "assertion",
                                    "label": "==",
                                    "description": "Passing assertion",
                                    "type_expected": "int",
                                    "passed": True,
                                    "type_actual": "int",
                                    "category": "DEFAULT",
                                    "second": 1,
                                    "type": "Equal",
                                    "first": 1,
                                    "utc_time": "",
                                    "line_no": 0,
                                }
                            ],
                        },
                        {
                            "status_reason": None,
                            "suite_related": False,
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "description": None,
                            "runtime_status": "ready",
                            "tags": {},
                            "timer": {},
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "category": "testcase",
                            "status_override": None,
                            "logs": [],
                            "uid": "basic_case__arg_2",
                            "name": "basic_case <arg=2>",
                            "status": "unknown",
                            "type": "TestCaseReport",
                            "hash": 0,
                            "entries": [],
                        },
                    ],
                    "env_status": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test1", "BasicSuite"],
                    "uid": "basic_case",
                    "strict_order": False,
                    "hash": 0,
                    "description": None,
                    "name": "basic_case",
                    "type": "TestGroupReport",
                }
            ],
            "env_status": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "parent_uids": ["InteractivePlan", "Test1"],
            "uid": "BasicSuite",
            "strict_order": False,
            "hash": 0,
            "description": None,
            "name": "BasicSuite",
            "type": "TestGroupReport",
        },
        {
            "status_reason": None,
            "counter": Counter(
                {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
            ),
            "runtime_status": "ready",
            "tags": {},
            "timer": {},
            "category": "testsuite",
            "status_override": None,
            "logs": [],
            "part": None,
            "status": "unknown",
            "entries": [
                {
                    "status_reason": None,
                    "suite_related": False,
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "description": "Client sends a message, server received and responds back.",
                    "runtime_status": "ready",
                    "tags": {},
                    "timer": {},
                    "parent_uids": ["InteractivePlan", "Test1", "Custom_0"],
                    "category": "testcase",
                    "status_override": None,
                    "logs": [],
                    "uid": "send_and_receive_msg",
                    "name": "send_and_receive_msg",
                    "status": "unknown",
                    "type": "TestCaseReport",
                    "hash": 0,
                    "entries": [],
                }
            ],
            "env_status": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "parent_uids": ["InteractivePlan", "Test1"],
            "uid": "Custom_0",
            "strict_order": False,
            "hash": 0,
            "description": None,
            "name": "Custom_0",
            "type": "TestGroupReport",
        },
        {
            "status_reason": None,
            "counter": Counter(
                {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
            ),
            "runtime_status": "ready",
            "tags": {},
            "timer": {},
            "category": "testsuite",
            "status_override": None,
            "logs": [],
            "part": None,
            "status": "unknown",
            "entries": [
                {
                    "status_reason": None,
                    "suite_related": False,
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "description": "Client sends a message, server received and responds back.",
                    "runtime_status": "ready",
                    "tags": {},
                    "timer": {},
                    "parent_uids": ["InteractivePlan", "Test1", "Custom_1"],
                    "category": "testcase",
                    "status_override": None,
                    "logs": [],
                    "uid": "send_and_receive_msg",
                    "name": "send_and_receive_msg",
                    "status": "unknown",
                    "type": "TestCaseReport",
                    "hash": 0,
                    "entries": [],
                }
            ],
            "env_status": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "parent_uids": ["InteractivePlan", "Test1"],
            "uid": "Custom_1",
            "strict_order": False,
            "hash": 0,
            "description": None,
            "name": "Custom_1",
            "type": "TestGroupReport",
        },
    ],
    "env_status": "STARTED",
    "fix_spec_path": None,
    "host": None,
    "events": {},
    "parent_uids": ["InteractivePlan"],
    "uid": "Test1",
    "strict_order": False,
    "hash": 0,
    "description": None,
    "name": "Test1",
    "type": "TestGroupReport",
}
