from collections import Counter

REPORT = {
    "strict_order": False,
    "status_override": None,
    "env_status": "STARTED",
    "status_reason": None,
    "fix_spec_path": None,
    "host": None,
    "events": {},
    "uid": "Test2",
    "entries": [
        {
            "strict_order": False,
            "status_override": None,
            "env_status": None,
            "status_reason": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "uid": "BasicSuite",
            "entries": [
                {
                    "strict_order": False,
                    "status_override": None,
                    "env_status": None,
                    "status_reason": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "uid": "basic_case",
                    "entries": [
                        {
                            "logs": [],
                            "status_override": None,
                            "suite_related": False,
                            "runtime_status": "ready",
                            "timer": {},
                            "tags": {},
                            "description": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "status": "unknown",
                            "category": "testcase",
                            "status_reason": None,
                            "name": "basic_case <arg=0>",
                            "uid": "basic_case__arg_0",
                            "type": "TestCaseReport",
                            "entries": [],
                            "hash": 0,
                        },
                        {
                            "logs": [],
                            "status_override": None,
                            "suite_related": False,
                            "runtime_status": "ready",
                            "timer": {},
                            "tags": {},
                            "description": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "status": "unknown",
                            "category": "testcase",
                            "status_reason": None,
                            "name": "basic_case <arg=1>",
                            "uid": "basic_case__arg_1",
                            "type": "TestCaseReport",
                            "entries": [],
                            "hash": 0,
                        },
                        {
                            "logs": [],
                            "status_override": None,
                            "suite_related": False,
                            "runtime_status": "ready",
                            "timer": {},
                            "tags": {},
                            "description": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "BasicSuite",
                                "basic_case",
                            ],
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "status": "unknown",
                            "category": "testcase",
                            "status_reason": None,
                            "name": "basic_case <arg=2>",
                            "uid": "basic_case__arg_2",
                            "type": "TestCaseReport",
                            "entries": [],
                            "hash": 0,
                        },
                    ],
                    "counter": Counter(
                        {"total": 3, "unknown": 3, "passed": 0, "failed": 0}
                    ),
                    "part": None,
                    "status": "unknown",
                    "type": "TestGroupReport",
                    "timer": {},
                    "runtime_status": "ready",
                    "description": None,
                    "category": "parametrization",
                    "name": "basic_case",
                    "logs": [],
                    "tags": {},
                    "parent_uids": ["InteractivePlan", "Test2", "BasicSuite"],
                    "hash": 0,
                }
            ],
            "counter": Counter(
                {"total": 3, "unknown": 3, "passed": 0, "failed": 0}
            ),
            "part": None,
            "status": "unknown",
            "type": "TestGroupReport",
            "timer": {},
            "runtime_status": "ready",
            "description": None,
            "category": "testsuite",
            "name": "BasicSuite",
            "logs": [],
            "tags": {},
            "parent_uids": ["InteractivePlan", "Test2"],
            "hash": 0,
        },
        {
            "strict_order": False,
            "status_override": None,
            "env_status": None,
            "status_reason": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "uid": "Custom_0",
            "entries": [
                {
                    "logs": [],
                    "status_override": None,
                    "suite_related": False,
                    "runtime_status": "ready",
                    "timer": {},
                    "tags": {},
                    "description": "Client sends a message, server received and responds back.",
                    "parent_uids": ["InteractivePlan", "Test2", "Custom_0"],
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "status": "unknown",
                    "category": "testcase",
                    "status_reason": None,
                    "name": "send_and_receive_msg",
                    "uid": "send_and_receive_msg",
                    "type": "TestCaseReport",
                    "entries": [],
                    "hash": 0,
                }
            ],
            "counter": Counter(
                {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
            ),
            "part": None,
            "status": "unknown",
            "type": "TestGroupReport",
            "timer": {},
            "runtime_status": "ready",
            "description": None,
            "category": "testsuite",
            "name": "Custom_0",
            "logs": [],
            "tags": {},
            "parent_uids": ["InteractivePlan", "Test2"],
            "hash": 0,
        },
        {
            "strict_order": False,
            "status_override": None,
            "env_status": None,
            "status_reason": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "uid": "Custom_1",
            "entries": [
                {
                    "logs": [],
                    "status_override": None,
                    "suite_related": False,
                    "runtime_status": "ready",
                    "timer": {},
                    "tags": {},
                    "description": "Client sends a message, server received and responds back.",
                    "parent_uids": ["InteractivePlan", "Test2", "Custom_1"],
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "status": "unknown",
                    "category": "testcase",
                    "status_reason": None,
                    "name": "send_and_receive_msg",
                    "uid": "send_and_receive_msg",
                    "type": "TestCaseReport",
                    "entries": [],
                    "hash": 0,
                }
            ],
            "counter": Counter(
                {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
            ),
            "part": None,
            "status": "unknown",
            "type": "TestGroupReport",
            "timer": {},
            "runtime_status": "ready",
            "description": None,
            "category": "testsuite",
            "name": "Custom_1",
            "logs": [],
            "tags": {},
            "parent_uids": ["InteractivePlan", "Test2"],
            "hash": 0,
        },
    ],
    "counter": Counter({"total": 5, "unknown": 5, "passed": 0, "failed": 0}),
    "part": None,
    "status": "unknown",
    "type": "TestGroupReport",
    "timer": {},
    "runtime_status": "ready",
    "description": None,
    "category": "multitest",
    "name": "Test2",
    "logs": [],
    "tags": {},
    "parent_uids": ["InteractivePlan"],
    "hash": 0,
}
