from collections import Counter

REPORT = {
    "description": None,
    "status_override": None,
    "name": "InteractivePlan",
    "information": [],
    "attachments": {},
    "uid": "InteractivePlan",
    "logs": [],
    "counter": Counter({"total": 10, "unknown": 10, "passed": 0, "failed": 0}),
    "entries": [
        {
            "counter": Counter(
                {"total": 5, "unknown": 5, "passed": 0, "failed": 0}
            ),
            "category": "multitest",
            "fix_spec_path": None,
            "name": "Test1",
            "type": "TestGroupReport",
            "status": "unknown",
            "strict_order": False,
            "logs": [],
            "part": None,
            "hash": 0,
            "description": None,
            "status_override": None,
            "entries": [
                {
                    "counter": Counter(
                        {"total": 3, "unknown": 3, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "BasicSuite",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {
                                    "total": 3,
                                    "unknown": 3,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "category": "parametrization",
                            "fix_spec_path": None,
                            "name": "basic_case",
                            "type": "TestGroupReport",
                            "status": "unknown",
                            "strict_order": False,
                            "logs": [],
                            "part": None,
                            "hash": 0,
                            "description": None,
                            "status_override": None,
                            "entries": [
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=0>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_0",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=1>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_1",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=2>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_2",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                            ],
                            "uid": "basic_case",
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "BasicSuite",
                            ],
                            "timer": {},
                            "tags": {},
                            "env_status": None,
                            "runtime_status": "ready",
                            "status_reason": None,
                        }
                    ],
                    "uid": "BasicSuite",
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
                {
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "Custom_0",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "description": "Client sends a message, server received and responds back.",
                            "status_override": None,
                            "name": "send_and_receive_msg",
                            "entries": [],
                            "logs": [],
                            "uid": "send_and_receive_msg",
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "Custom_0",
                            ],
                            "category": "testcase",
                            "timer": {},
                            "tags": {},
                            "type": "TestCaseReport",
                            "status": "unknown",
                            "hash": 0,
                            "runtime_status": "ready",
                            "suite_related": False,
                            "status_reason": None,
                        }
                    ],
                    "uid": "Custom_0",
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
                {
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "Custom_1",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "description": "Client sends a message, server received and responds back.",
                            "status_override": None,
                            "name": "send_and_receive_msg",
                            "entries": [],
                            "logs": [],
                            "uid": "send_and_receive_msg",
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "Custom_1",
                            ],
                            "category": "testcase",
                            "timer": {},
                            "tags": {},
                            "type": "TestCaseReport",
                            "status": "unknown",
                            "hash": 0,
                            "runtime_status": "ready",
                            "suite_related": False,
                            "status_reason": None,
                        }
                    ],
                    "uid": "Custom_1",
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
            ],
            "uid": "Test1",
            "parent_uids": ["InteractivePlan"],
            "timer": {},
            "tags": {},
            "env_status": "STOPPED",
            "runtime_status": "ready",
            "status_reason": None,
        },
        {
            "counter": Counter(
                {"total": 5, "unknown": 5, "passed": 0, "failed": 0}
            ),
            "category": "multitest",
            "fix_spec_path": None,
            "name": "Test2",
            "type": "TestGroupReport",
            "status": "unknown",
            "strict_order": False,
            "logs": [],
            "part": None,
            "hash": 0,
            "description": None,
            "status_override": None,
            "entries": [
                {
                    "counter": Counter(
                        {"total": 3, "unknown": 3, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "BasicSuite",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {
                                    "total": 3,
                                    "unknown": 3,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "category": "parametrization",
                            "fix_spec_path": None,
                            "name": "basic_case",
                            "type": "TestGroupReport",
                            "status": "unknown",
                            "strict_order": False,
                            "logs": [],
                            "part": None,
                            "hash": 0,
                            "description": None,
                            "status_override": None,
                            "entries": [
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=0>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_0",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=1>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_1",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                                {
                                    "description": None,
                                    "status_override": None,
                                    "name": "basic_case <arg=2>",
                                    "entries": [],
                                    "logs": [],
                                    "uid": "basic_case__arg_2",
                                    "counter": Counter(
                                        {
                                            "total": 1,
                                            "unknown": 1,
                                            "passed": 0,
                                            "failed": 0,
                                        }
                                    ),
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "category": "testcase",
                                    "timer": {},
                                    "tags": {},
                                    "type": "TestCaseReport",
                                    "status": "unknown",
                                    "hash": 0,
                                    "runtime_status": "ready",
                                    "suite_related": False,
                                    "status_reason": None,
                                },
                            ],
                            "uid": "basic_case",
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "BasicSuite",
                            ],
                            "timer": {},
                            "tags": {},
                            "env_status": None,
                            "runtime_status": "ready",
                            "status_reason": None,
                        }
                    ],
                    "uid": "BasicSuite",
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
                {
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "Custom_0",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "description": "Client sends a message, server received and responds back.",
                            "status_override": None,
                            "name": "send_and_receive_msg",
                            "entries": [],
                            "logs": [],
                            "uid": "send_and_receive_msg",
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "Custom_0",
                            ],
                            "category": "testcase",
                            "timer": {},
                            "tags": {},
                            "type": "TestCaseReport",
                            "status": "unknown",
                            "hash": 0,
                            "runtime_status": "ready",
                            "suite_related": False,
                            "status_reason": None,
                        }
                    ],
                    "uid": "Custom_0",
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
                {
                    "counter": Counter(
                        {"total": 1, "unknown": 1, "passed": 0, "failed": 0}
                    ),
                    "category": "testsuite",
                    "fix_spec_path": None,
                    "name": "Custom_1",
                    "type": "TestGroupReport",
                    "status": "unknown",
                    "strict_order": False,
                    "logs": [],
                    "part": None,
                    "hash": 0,
                    "description": None,
                    "status_override": None,
                    "entries": [
                        {
                            "description": "Client sends a message, server received and responds back.",
                            "status_override": None,
                            "name": "send_and_receive_msg",
                            "entries": [],
                            "logs": [],
                            "uid": "send_and_receive_msg",
                            "counter": Counter(
                                {
                                    "total": 1,
                                    "unknown": 1,
                                    "passed": 0,
                                    "failed": 0,
                                }
                            ),
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "Custom_1",
                            ],
                            "category": "testcase",
                            "timer": {},
                            "tags": {},
                            "type": "TestCaseReport",
                            "status": "unknown",
                            "hash": 0,
                            "runtime_status": "ready",
                            "suite_related": False,
                            "status_reason": None,
                        }
                    ],
                    "uid": "Custom_1",
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "timer": {},
                    "tags": {},
                    "env_status": None,
                    "runtime_status": "ready",
                    "status_reason": None,
                },
            ],
            "uid": "Test2",
            "parent_uids": ["InteractivePlan"],
            "timer": {},
            "tags": {},
            "env_status": "STOPPED",
            "runtime_status": "ready",
            "status_reason": None,
        },
    ],
    "category": "testplan",
    "timer": {},
    "tags_index": {},
    "timeout": None,
    "status": "unknown",
    "runtime_status": "ready",
    "meta": {},
    "label": None,
}
