REPORT = {
    u"attachments": {},
    u"entries": [
        {
            u"category": u"multitest",
            u"description": None,
            u"entries": [
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"category": u"parametrization",
                            u"description": None,
                            u"entries": [
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_0",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_0",
                                },
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_1",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_1",
                                },
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_2",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_2",
                                },
                            ],
                            u"fix_spec_path": None,
                            u"logs": [],
                            u"name": u"basic_case",
                            u"part": None,
                            u"status": u"incomplete",
                            u"status_override": None,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestGroupReport",
                            u"uid": u"basic_case",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"BasicSuite",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"BasicSuite",
                },
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"description": u"\n        Client sends a message, server received and responds back.\n        ",
                            u"entries": [],
                            u"logs": [],
                            u"name": u"send_and_receive_msg",
                            u"status": u"incomplete",
                            u"status_override": u"incomplete",
                            u"suite_related": False,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestCaseReport",
                            u"uid": u"send_and_receive_msg",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"TCPSuite - Custom_0",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"TCPSuite - Custom_0",
                },
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"description": u"\n        Client sends a message, server received and responds back.\n        ",
                            u"entries": [],
                            u"logs": [],
                            u"name": u"send_and_receive_msg",
                            u"status": u"incomplete",
                            u"status_override": u"incomplete",
                            u"suite_related": False,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestCaseReport",
                            u"uid": u"send_and_receive_msg",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"TCPSuite - Custom_1",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"TCPSuite - Custom_1",
                },
            ],
            u"fix_spec_path": None,
            u"logs": [],
            u"name": u"Test1",
            u"part": None,
            u"status": u"incomplete",
            u"status_override": None,
            u"tags": {},
            u"timer": {},
            u"type": "TestGroupReport",
            u"uid": u"Test1",
        },
        {
            u"category": u"multitest",
            u"description": None,
            u"entries": [
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"category": u"parametrization",
                            u"description": None,
                            u"entries": [
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_0",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_0",
                                },
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_1",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_1",
                                },
                                {
                                    u"description": None,
                                    u"entries": [],
                                    u"logs": [],
                                    u"name": u"basic_case__arg_2",
                                    u"status": u"incomplete",
                                    u"status_override": u"incomplete",
                                    u"suite_related": False,
                                    u"tags": {},
                                    u"timer": {},
                                    u"type": "TestCaseReport",
                                    u"uid": u"basic_case__arg_2",
                                },
                            ],
                            u"fix_spec_path": None,
                            u"logs": [],
                            u"name": u"basic_case",
                            u"part": None,
                            u"status": u"incomplete",
                            u"status_override": None,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestGroupReport",
                            u"uid": u"basic_case",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"BasicSuite",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"BasicSuite",
                },
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"description": u"\n        Client sends a message, server received and responds back.\n        ",
                            u"entries": [],
                            u"logs": [],
                            u"name": u"send_and_receive_msg",
                            u"status": u"incomplete",
                            u"status_override": u"incomplete",
                            u"suite_related": False,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestCaseReport",
                            u"uid": u"send_and_receive_msg",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"TCPSuite - Custom_0",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"TCPSuite - Custom_0",
                },
                {
                    u"category": u"testsuite",
                    u"description": None,
                    u"entries": [
                        {
                            u"description": u"\n        Client sends a message, server received and responds back.\n        ",
                            u"entries": [],
                            u"logs": [],
                            u"name": u"send_and_receive_msg",
                            u"status": u"incomplete",
                            u"status_override": u"incomplete",
                            u"suite_related": False,
                            u"tags": {},
                            u"timer": {},
                            u"type": "TestCaseReport",
                            u"uid": u"send_and_receive_msg",
                        }
                    ],
                    u"fix_spec_path": None,
                    u"logs": [],
                    u"name": u"TCPSuite - Custom_1",
                    u"part": None,
                    u"status": u"incomplete",
                    u"status_override": None,
                    u"tags": {},
                    u"timer": {},
                    u"type": "TestGroupReport",
                    u"uid": u"TCPSuite - Custom_1",
                },
            ],
            u"fix_spec_path": None,
            u"logs": [],
            u"name": u"Test2",
            u"part": None,
            u"status": u"incomplete",
            u"status_override": None,
            u"tags": {},
            u"timer": {},
            u"type": "TestGroupReport",
            u"uid": u"Test2",
        },
    ],
    u"meta": {},
    u"name": u"InteractivePlan",
    u"status": u"incomplete",
    u"status_override": None,
    u"tags_index": {},
    u"timer": {},
    u"uid": u"InteractivePlan",
}
