from collections import Counter

REPORT = {
    "information": [],
    "events": {},
    "status_override": None,
    "counter": Counter({"passed": 10, "total": 10, "failed": 0}),
    "name": "InteractivePlan",
    "entries": [
        {
            "name": "Test1",
            "status_reason": None,
            "env_status": "STARTED",
            "tags": {},
            "logs": [],
            "category": "multitest",
            "status_override": None,
            "entries": [
                {
                    "name": "BasicSuite",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "name": "basic_case",
                            "status_reason": None,
                            "env_status": None,
                            "tags": {},
                            "logs": [],
                            "category": "parametrization",
                            "status_override": None,
                            "entries": [
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=0>",
                                    "hash": 0,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_0",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=1>",
                                    "hash": 0,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_1",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=2>",
                                    "hash": 904824446777638636,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test1",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_2",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                            ],
                            "strict_order": False,
                            "status": "passed",
                            "runtime_status": "finished",
                            "part": None,
                            "fix_spec_path": None,
                            "host": None,
                            "events": {},
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "BasicSuite",
                            ],
                            "type": "TestGroupReport",
                            "counter": Counter(
                                {"passed": 3, "total": 3, "failed": 0}
                            ),
                            "hash": 0,
                            "description": None,
                            "timer": {},
                            "uid": "basic_case",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 3, "total": 3, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "BasicSuite",
                },
                {
                    "name": "Custom_0",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {"passed": 1, "total": 1, "failed": 0}
                            ),
                            "status_override": None,
                            "entries": [
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Server received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "hello",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "hello",
                                    "category": "DEFAULT",
                                },
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Client received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "world",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "world",
                                    "category": "DEFAULT",
                                },
                            ],
                            "name": "send_and_receive_msg",
                            "hash": 0,
                            "status_reason": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "Custom_0",
                            ],
                            "description": "Client sends a message, server received and responds back.",
                            "timer": {
                                "run": {
                                    "start": "",
                                    "end": "",
                                }
                            },
                            "uid": "send_and_receive_msg",
                            "tags": {},
                            "status": "passed",
                            "type": "TestCaseReport",
                            "runtime_status": "finished",
                            "suite_related": False,
                            "logs": [],
                            "category": "testcase",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 1, "total": 1, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "Custom_0",
                },
                {
                    "name": "Custom_1",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {"passed": 1, "total": 1, "failed": 0}
                            ),
                            "status_override": None,
                            "entries": [
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Server received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "hello",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "hello",
                                    "category": "DEFAULT",
                                },
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Client received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "world",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "world",
                                    "category": "DEFAULT",
                                },
                            ],
                            "name": "send_and_receive_msg",
                            "hash": 0,
                            "status_reason": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test1",
                                "Custom_1",
                            ],
                            "description": "Client sends a message, server received and responds back.",
                            "timer": {
                                "run": {
                                    "start": "",
                                    "end": "",
                                }
                            },
                            "uid": "send_and_receive_msg",
                            "tags": {},
                            "status": "passed",
                            "type": "TestCaseReport",
                            "runtime_status": "finished",
                            "suite_related": False,
                            "logs": [],
                            "category": "testcase",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test1"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 1, "total": 1, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "Custom_1",
                },
            ],
            "strict_order": False,
            "status": "passed",
            "runtime_status": "finished",
            "part": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "parent_uids": ["InteractivePlan"],
            "type": "TestGroupReport",
            "counter": Counter({"passed": 5, "total": 5, "failed": 0}),
            "hash": 0,
            "description": None,
            "timer": {},
            "uid": "Test1",
        },
        {
            "name": "Test2",
            "status_reason": None,
            "env_status": "STARTED",
            "tags": {},
            "logs": [],
            "category": "multitest",
            "status_override": None,
            "entries": [
                {
                    "name": "BasicSuite",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "name": "basic_case",
                            "status_reason": None,
                            "env_status": None,
                            "tags": {},
                            "logs": [],
                            "category": "parametrization",
                            "status_override": None,
                            "entries": [
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=0>",
                                    "hash": 0,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_0",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=1>",
                                    "hash": 0,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_1",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                                {
                                    "counter": Counter(
                                        {"passed": 1, "total": 1, "failed": 0}
                                    ),
                                    "status_override": None,
                                    "entries": [
                                        {
                                            "machine_time": "",
                                            "passed": True,
                                            "type_expected": "int",
                                            "flag": "DEFAULT",
                                            "description": "Passing assertion",
                                            "meta_type": "assertion",
                                            "line_no": 0,
                                            "first": 1,
                                            "utc_time": "",
                                            "label": "==",
                                            "type": "Equal",
                                            "type_actual": "int",
                                            "second": 1,
                                            "category": "DEFAULT",
                                        }
                                    ],
                                    "name": "basic_case <arg=2>",
                                    "hash": 0,
                                    "status_reason": None,
                                    "parent_uids": [
                                        "InteractivePlan",
                                        "Test2",
                                        "BasicSuite",
                                        "basic_case",
                                    ],
                                    "description": None,
                                    "timer": {
                                        "run": {
                                            "start": "",
                                            "end": "",
                                        }
                                    },
                                    "uid": "basic_case__arg_2",
                                    "tags": {},
                                    "status": "passed",
                                    "type": "TestCaseReport",
                                    "runtime_status": "finished",
                                    "suite_related": False,
                                    "logs": [],
                                    "category": "testcase",
                                },
                            ],
                            "strict_order": False,
                            "status": "passed",
                            "runtime_status": "finished",
                            "part": None,
                            "fix_spec_path": None,
                            "host": None,
                            "events": {},
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "BasicSuite",
                            ],
                            "type": "TestGroupReport",
                            "counter": Counter(
                                {"passed": 3, "total": 3, "failed": 0}
                            ),
                            "hash": 0,
                            "description": None,
                            "timer": {},
                            "uid": "basic_case",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 3, "total": 3, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "BasicSuite",
                },
                {
                    "name": "Custom_0",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {"passed": 1, "total": 1, "failed": 0}
                            ),
                            "status_override": None,
                            "entries": [
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Server received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "hello",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "hello",
                                    "category": "DEFAULT",
                                },
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Client received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "world",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "world",
                                    "category": "DEFAULT",
                                },
                            ],
                            "name": "send_and_receive_msg",
                            "hash": 0,
                            "status_reason": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "Custom_0",
                            ],
                            "description": "Client sends a message, server received and responds back.",
                            "timer": {
                                "run": {
                                    "start": "",
                                    "end": "",
                                }
                            },
                            "uid": "send_and_receive_msg",
                            "tags": {},
                            "status": "passed",
                            "type": "TestCaseReport",
                            "runtime_status": "finished",
                            "suite_related": False,
                            "logs": [],
                            "category": "testcase",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 1, "total": 1, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "Custom_0",
                },
                {
                    "name": "Custom_1",
                    "status_reason": None,
                    "env_status": None,
                    "tags": {},
                    "logs": [],
                    "category": "testsuite",
                    "status_override": None,
                    "entries": [
                        {
                            "counter": Counter(
                                {"passed": 1, "total": 1, "failed": 0}
                            ),
                            "status_override": None,
                            "entries": [
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Server received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "hello",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "hello",
                                    "category": "DEFAULT",
                                },
                                {
                                    "machine_time": "",
                                    "passed": True,
                                    "type_expected": "str",
                                    "flag": "DEFAULT",
                                    "description": "Client received",
                                    "meta_type": "assertion",
                                    "line_no": 0,
                                    "first": "world",
                                    "utc_time": "",
                                    "label": "==",
                                    "type": "Equal",
                                    "type_actual": "str",
                                    "second": "world",
                                    "category": "DEFAULT",
                                },
                            ],
                            "name": "send_and_receive_msg",
                            "hash": 0,
                            "status_reason": None,
                            "parent_uids": [
                                "InteractivePlan",
                                "Test2",
                                "Custom_1",
                            ],
                            "description": "Client sends a message, server received and responds back.",
                            "timer": {
                                "run": {
                                    "start": "",
                                    "end": "",
                                }
                            },
                            "uid": "send_and_receive_msg",
                            "tags": {},
                            "status": "passed",
                            "type": "TestCaseReport",
                            "runtime_status": "finished",
                            "suite_related": False,
                            "logs": [],
                            "category": "testcase",
                        }
                    ],
                    "strict_order": False,
                    "status": "passed",
                    "runtime_status": "finished",
                    "part": None,
                    "fix_spec_path": None,
                    "host": None,
                    "events": {},
                    "parent_uids": ["InteractivePlan", "Test2"],
                    "type": "TestGroupReport",
                    "counter": Counter({"passed": 1, "total": 1, "failed": 0}),
                    "hash": 0,
                    "description": None,
                    "timer": {},
                    "uid": "Custom_1",
                },
            ],
            "strict_order": False,
            "status": "passed",
            "runtime_status": "finished",
            "part": None,
            "fix_spec_path": None,
            "host": None,
            "events": {},
            "parent_uids": ["InteractivePlan"],
            "type": "TestGroupReport",
            "counter": Counter({"passed": 5, "total": 5, "failed": 0}),
            "hash": 0,
            "description": None,
            "timer": {},
            "uid": "Test2",
        },
    ],
    "description": None,
    "timeout": None,
    "timer": {},
    "uid": "InteractivePlan",
    "label": None,
    "tags_index": {},
    "status": "passed",
    "runtime_status": "finished",
    "meta": {},
    "logs": [],
    "attachments": {},
    "category": "testplan",
}
